### ISSUE TITLE
Exception when trying to use term-color:set

### ISSUE THREAD

**Issue by muesli** [chlorm/elvish-color-schemes#2]
Following the README, I run into this exception with latest elvish master. Note that I'm running this in konsole, no gnome-terminal installed.

```
\\\\\\\\\\\\\\\\Exception: arity mismatch
Traceback:
  /home/muesli/.elvish/lib/github.com/chlorm/elvish-term-color/term-color.elv, line 46:
      profile = (dconf list /org/gnome/terminal/legacy/profiles:/)
  /home/muesli/.elvish/lib/github.com/chlorm/elvish-term-color/term-color.elv, line 135:
        set-gnome-terminal $x
  /home/muesli/.elvish/lib/github.com/chlorm/elvish-term-color/term-color.elv, line 134-136:
      if (and (has-env DISPLAY) (has-external dconf)) {
        set-gnome-terminal $x
      }
  [tty], line 1:
    term-color:set (color-scheme:monokai)
```

**Comment by codyopel** [comment]
I haven't gotten around to testing this on other terminal emulators yet.  The main issue is that it currently assumes gnome-terminal exists if dconf exists, I added a check in https://github.com/chlorm/elvish-term-color/commit/3dcdfb3557de9862d29b52180b2860da7830e0b6 that will avoid the issue.  It can still fail if gnome-terminal is installed, but the dconf entries are missing.  I'll fix that at some point.

I am not sure how konsole defines colors if it is via dconf or a flat config file.  Since it is VTE based, if you use X11 the X11 method will work, however I don't think VTE translates the OSC escape sequences, so it may not work on Wayland.

**Comment by muesli** [comment]
I actually still get the same arity mismatch. Fwiw, `dconf list /org/gnome/terminal/legacy/profiles:/` exists cleanly but doesn't output anything (as there probably aren't any gnome-terminal profiles to be found).

Thanks for looking into this!

**Comment by codyopel** [comment]
Fixed in https://github.com/chlorm/elvish-term-color/commit/365218af5bb248a204f1a705e8a436fdd8de452a

**Comment by muesli** [comment]
Confirmed as fixed, interestingly I'm still seeing this output:

```
\\\\\\\\\\\\\\\\
```

**Comment by codyopel** [comment]
I can't reproduce it with VTE 0.50.2, or st.  However it is probably the second escape not being interpreted correctly and being printed from:
https://github.com/chlorm/elvish-term-color/blob/365218af5bb248a204f1a705e8a436fdd8de452a/term-color.elv#L110

I changed the termination for the escape sequence so hopefully it works now.
https://github.com/chlorm/elvish-term-color/commit/a715ace4673e97e3053c7fad3359ceb481b83e42

**Comment by muesli** [comment]
Fixed indeed, thank you!
